### ISSUE TITLE
pip install error -stdlib=libc++

### ISSUE THREAD

**Issue by Shimwell** [fmder/ghalton#14]
Does anyone else get this install error

`    x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-stdlib=libc++’
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`
![Screenshot from 2020-01-27 08-57-19](https://user-images.githubusercontent.com/8583900/73161273-0e4e7c80-40e3-11ea-8c25-271126f653af.png)

**Comment by Shimwell** [comment]
Just for extra information, I don't get this install error with the previous version

pip3 install ghalton==0.6.1

**Comment by brq12** [comment]
`pip3 install --upgrade pip` fixes the problem

**Comment by Shimwell** [comment]
thanks

**Comment by cserpell** [comment]
In new version of pip it does not work, see https://github.com/fmder/ghalton/issues/16#issuecomment-1399347105
