### ISSUE TITLE
pip install failed inside docker for python3.6

### ISSUE THREAD

**Issue by n3011** [fmder/ghalton#8]
using docker ubuntu 16.04 image 
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zg4cpout/ghalton/setup.py", line 15, in <module>
        long_description = open("README.md").read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2730: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zg4cpout/ghalton/

**Comment by liz2020** [comment]
Hi, I also encounter this issue and fix it by specifying the encoding in setup.py. You can find out the change at [here](https://github.com/fmder/ghalton/pull/7/files).

**Comment by fmder** [comment]
Fixed in #7
